CREATE TABLE SHOP_ORDER(
    ID NUMBER,
    ORDERLIST VARCHAR2(1000 CHAR),
    BUYERNAME VARCHAR2(15 CHAR),
    PACKAGENAME VARCHAR2(15 CHAR),
    ADDRESS VARCHAR2(100 CHAR),
    POSTNUMBER NUMBER,
    PHONENUMBER NUMBER,
    PAYMETHOD VARCHAR2(15 CHAR),
    PRICE NUMBER,
    ORDERNO VARCHAR2(30 CHAR),
    ORDERSTATE NUMBER,
    PACKAGENO NUMBER
);

CREATE SEQUENCE SHOP_ORDER_SEQ NOCACHE;