CREATE TABLE SHOP_SELLER_ORDER(
    ID NUMBER,
    ORDERID NUMBER,
    SELLERID NUMBER,
    ORDERNO VARCHAR2(30 CHAR),
    ITEMLIST VARCHAR2(1000 CHAR)
);

ALTER TABLE SHOP_SELLER_ORDER ADD CONSTRAINT SHOP_SELLER_ORDER_ID_PK PRIMARY KEY(ID);
ALTER TABLE SHOP_SELLER_ORDER ADD CONSTRAINT 
    SHOP_SELLER_ORDER_SELLERID_FK FOREIGN KEY(SELLERID) REFERENCES SHOP_ACCOUNTS(ID);
ALTER TABLE SHOP_SELLER_ORDER ADD CONSTRAINT 
    SHOP_SELLER_ORDER_ORDERID_FK FOREIGN KEY(ORDERID) REFERENCES SHOP_ORDER(ID);

CREATE SEQUENCE SHOP_SELLER_ORDER_SEQ NOCACHE;

SELECT * FROM SHOP_SELLER_ORDER;