CREATE TABLE SHOP_ORDERSTAT(
    ID NUMBER,
    ORDERST VARCHAR2(15 CHAR)
);

CREATE SEQUENCE SHOP_ORDERSTAT_SEQ NOCACHE;

INSERT INTO SHOP_ORDERSTAT VALUES(
    SHOP_ORDERSTAT_SEQ.NEXTVAL,
    '입금대기'
);

INSERT INTO SHOP_ORDERSTAT VALUES(
    0,
    '주문취소'
);

SELECT * FROM SHOP_ORDERSTAT;

DELETE FROM SHOP_ORDERSTAT WHERE ID = 9;